### ISSUE TITLE
Drone build containers cannot access bitbucket repos.

### ISSUE THREAD

**Issue by kubilus1** [Phillaf/bitbucket-drone#1]
Unfortunately, it appears that drone build containers do not connect to the docker network in the docker-compose leading to errors like:

```
+ git fetch --no-tags origin +refs/heads/master:
fatal: unable to access 'http://bitbucket:7990/scm/tst/arepo.git/': Failed to connect to bitbucket port 7990: Operation timed out
exit status 128
```

**Comment by Phillaf** [comment]
Can you post your full docker-compose file?

**Comment by kubilus1** [comment]
Some more info:

docker-compose.yml:

```
version: "2"
services:

  bitbucket:
    image: atlassian/bitbucket-server
    ports:
      - 7990:7990
      - 7999:7999
    volumes:
      - ./bitbucket:/var/atlassian/application-data/bitbucket

  drone-server:
    image: drone/drone:0.8
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server
      - DRONE_STASH=true
      - DRONE_STASH_GIT_USERNAME=drone
      - DRONE_STASH_GIT_PASSWORD=drone
      - DRONE_STASH_CONSUMER_KEY=95c0282573633eb25e82
      - DRONE_STASH_CONSUMER_RSA=/etc/bitbucket/key.pem
      - DRONE_STASH_URL=http://bitbucket:7990
      - DRONE_SECRET=123456
    volumes:
      - ./drone:/var/lib/drone/
      - ./bitbucketkey.pem:/etc/bitbucket/key.pem

  drone-agent:
    image: drone/agent:0.8
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=123456
```

Sample .drone.yml:

```
pipeline: 
  build:
    image: python:3.5.1-alpine
    commands:
      - python -c "print 'Hello World!'"
```

I also tried adding a 'networks' section to the drone.yml (based on compose afterall) but no difference in result:

```
pipeline: 
  build:
    image: python:3.5.1-alpine
    commands:
      - python -c "print 'Hello World!'"

networks:
  default:
    external:
      name: bitbucketdrone_default
```

Entering the build container during a build and attempting to ping the 'bitbucket' container proves out that the two are not connected.
